package th.ac.utcc.cpe.data_structures.sample;
import java.util.Scanner;
/**
 * แก้ไขให้เป็นชื่อและอีเมล์ของตัวเอง
 * @author Peerapong Tippanun <1910711102018@live4.utcc.ac.th>
 */
public class MainFrame extends javax.swing.JFrame {
    private MyDict myDict;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        initMyDict();
    }
    
    private void initMyDict() {
    	Scanner input = new Scanner(System.in);
        myDict = new MyDict();
        Tree dic = new Tree();
        dic.insert("cat","a small animal with soft fur that people often keep as a pet. Cats catch and kill birds and mice.");
        dic.insert("pen","an instrument made of plastic or metal used for writing with ink");
        dic.insert("system","an organized set of ideas or theories or a particular way of doing something");
        dic.insert("out","away from the inside of a place or thing");
        dic.insert("print","to produce letters, pictures, etc. on paper using a machine that puts ink on the surface");
        dic.insert("hello","used as a greeting when you meet somebody, when you answer the telephone or when you want to attract somebody’s attention");
        dic.insert("easy","not difficult; done or obtained without a lot of effort or problems");
        dic.insert("max","maximum,at the most");
        dic.insert("computer","an electronic machine that can store, organize and find information, do calculations and control other machines");
        dic.insert("multimedia","the use of sound, pictures and film in addition to text on a screen");
        int i =0;
        while(i==0) {
        
         System.out.println("---------Dictionary---------\n"
          + "1---> find\n"
          + "2---> delete\n"
          + "3---> insert word\n"
          + "4---> all word" );
         int a = input.nextInt();
         
         switch(a) {
          case 1 : 
           System.out.println("What is a word?");
           String find = input.next();
           Node f = dic.find(find);
           if(f != null) {
            System.out.println(f.iData);
            f.displayNode();
           }
           else System.out.println("Cann't found it");
          break;
         
          case 2 : 
           System.out.println("What is a word to you delete?");
           String del = input.next();
            dic.delete(del);
            dic.displayiDataInOder();
           
          break;
        
          case 3 : 
           System.out.println("What is a word to you insert?");
           String word = input.next();
           System.out.println("What dose it mean?");
           String mean = input.next();
            dic.insert(word, mean);
            dic.displayiDataInOder();
            break;
          
          case 4 :
              dic.displayiDataInOder();
          break;
          
          default:System.out.println("Error");
         }
        }
        // ปรับเปลี่ยนโค้ดที่นี่เพื่อเติมคำศัพท์
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tbxVocab = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaTranslation = new javax.swing.JTextArea();
        btnSearch = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("คำศัพท์:");

        tbxVocab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbxVocabActionPerformed(evt);
            }
        });

        txaTranslation.setColumns(20);
        txaTranslation.setRows(5);
        jScrollPane1.setViewportView(txaTranslation);

        btnSearch.setText("ค้นหา");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel2.setText("คำแปล:");

        btnExit.setText("จบโปรแกรม");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(tbxVocab)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExit)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnExit, btnSearch});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tbxVocab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit)
                    .addComponent(btnSearch))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        searchPerformed();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tbxVocabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbxVocabActionPerformed
        searchPerformed();
    }//GEN-LAST:event_tbxVocabActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void searchPerformed() {
        String translation = myDict.find(this.tbxVocab.getText());
        this.txaTranslation.setText(translation);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tbxVocab;
    private javax.swing.JTextArea txaTranslation;
    // End of variables declaration//GEN-END:variables
}
